### ISSUE TITLE
Generate webhooks after a project is published

### ISSUE THREAD

**Issue by alexandermendes** [Scifabric/pybossa#1664] opened 2017-09-12 09:30 UTC
We now have a way to rerun all webhooks for a project, but this only applies if the webhooks URL was set when a task was completed. It would be great to also be able to update that webhook URL after tasks are completed. If the results analysis wasn't set up before the project was published we can't now trigger webhooks once it is set up. This would also make it possible to change ones mind and send webhooks to different endpoints.

Maybe webhooks can be generated for all completed tasks when the webhooks URL is updated?

**Comment by alexandermendes** [comment] 2017-09-13 15:26
I think I'll close this one and handle it through our analysis server instead, probably easier!

**Comment by teleyinex** [comment] 2017-09-14 08:03
It's not a bad idea. However, PYBOSSA creates the results as well. The issue is that if you don't want, you don't need the webhooks, as you can always use enki to get the tasks, task runs and update the created results. Let's keep it close, but I think it's worth a discussion.

**Comment by alexandermendes** [comment] 2017-09-14 08:09
Cool yeah, so I ended up think it was kind of innacurate to generate the 'task_completed event long after the task was actually completed. It could be nice to have something like this but can't think exactly how it would work.

**Comment by alexandermendes** [comment] 2017-09-14 09:24
Yeah I guess that could work!

So basically just move the `if project_obj['webhook']` bit here

https://github.com/Scifabric/pybossa/blob/a002c0d9f98ba9506c8edf5401a2622a0c955d94/pybossa/jobs.py#L530-L535

and do something about the subsequent CommectionError that would be raised here (maybe not raise it if it's actually None - only if something is entered that's not a url)?

https://github.com/Scifabric/pybossa/blob/a002c0d9f98ba9506c8edf5401a2622a0c955d94/pybossa/jobs.py#L530-L535

**Comment by teleyinex** [comment] 2017-09-14 09:32
If project_obj['webhook'] is None, then, create the payload, save it, but do not enqueue it.

**Comment by alexandermendes** [comment] 2017-09-14 09:36
Cool ok, that makes more sense. Shall we reopen then? I can submit a PR when I find a few mins!

**Comment by teleyinex** [comment] 2019-09-29 20:19
Hi,

Long time, but it's now fixed ;-) Check #1934 

Cheers,

Daniel

**Closed by teleyinex** 2019-09-29 20:19 UTC
Labels: priority.low
