### ISSUE TITLE
Same task is presented to different users, regardless of redundancy

### ISSUE THREAD

**Issue by ajallooeian** [Scifabric/pybossa#1523] opened 2017-03-31 09:43 UTC
Hi,

I have a pybossa server running locally, and when users are contributing, the see the same task, even if the redundancy is 1. 

I can regenerate the problem by making several users, opening pybossa in different browser sessions, and then try to contribute with the users at more-or-less the same time. They see the same task. 

Moreover, after this situation, the system becomes very slow...

**Comment by therealmarv** [comment] 2017-03-31 09:56
Hi @ajallooeian,
this is by design. Most crowdcrafting projects we see have more the problem to gain a good/critical number of people participating as a crowd. The problem that many people participate at the exact same time simultaneously in a big number is something which we see very seldom happening. It's also not a problem even for low redundancy because it won't hurt the taskruns output if a task is done over the redundancy requirement.
Also be aware that if you set redundancy to 1 you will get a statistical bad data output (because every wrong answer will impact your data set very strong with redundancy 1).

What you can look at is the [random scheduler plug-in](https://github.com/Scifabric/random-scheduler).

About the speed: If you see slowdowns please run PYBOSSA as UWSGI/nginx system service as described here http://docs.pybossa.com/en/latest/nginx.html (this is our advice for production systems)

Just FYI: If you want we offer also paid support on your project. We are happy to assist you. Contact info@scifabric.com if you are interested in that.

**Comment by teleyinex** [comment] 2017-03-31 11:18
Hi,

PYBOSSA serves always the same task to different users until it is marked as completed (this only happens when the number of answers equal the redundancy value). However, to reach this goal it needs to send this task to anyone requesting a task for a given project. 

Some people have suggested the idea of locking a task when sent to different users. However, this will end up with tasks that would not complete, or would take really long to complete if just one malicious user gets the task and never solves it. The lock will prevent the system to complete it. Moreover, for lots of projects it's almost impossible to know how long it's going to take to solve a task, as the problems they're solving are open ended, and therefore this "magic value" wont be calculated easily.

For your case it looks like the Random scheduler is great. However, be aware that we do not support it, as a user could get the same task twice after participating. This will lead to bad data analysis, so we only created the scheduler as a template for creating new schedulers via our PYBOSSA plugin system.

Take a look to our other PYBOSSA scheduler, breadth first, as it might be better for your case.

Regarding the speed: PYBOSSA is not configured by default with all the cache systems, and ready-production configurations. Please, check the official documentation from each service that PYBOSSA requires (Redis, Sentinel, Nginx, uswgi and PostgreSQL). As @therealmarv suggested we offer already configured servers that will cover your needs. Check our [services & products](https://scifabric.com/crowdsourcing/pybossa-cloud-servers/) page.

**Closed** 2017-04-03 07:36 UTC
